dist: xenial
language: node_js
node_js:
  - lts/*
  - 10
  - 8
cache:
  directories:
    - node_modules
script:
  - echo "Tests already run in 'npm ci' step so nothing left to do here."

# Added comment - 
